# In backend/crud.py

import random
import json # <-- ADD THIS IMPORT
import datetime # <-- ADD THIS IMPORT
from sqlalchemy.orm import Session
from sqlalchemy import func
from typing import Optional, List
import models
import security
# Corrected and specific imports for all schemas used in this file
from schemas.user import UserCreate
from schemas.notes import NoteCreate, Note 
from schemas.stats import UserStats, QuizHistoryItem
from schemas.nudge import DailyNudge
from schemas.quiz import QuizCreate, QuestionCreate, QuizAttemptSubmit, QuizResult # <-- ADD THIS IMPORT
from schemas.journal import JournalEntryCreate, JournalEntry as JournalEntrySchema
# --- User Functions ---
def get_user_by_email(db: Session, email: str):
    return db.query(models.User).filter(models.User.email == email).first()

def create_user(db: Session, user: UserCreate):
    # For Firebase auth, password might be empty
    hashed_password = security.get_password_hash(user.password) if user.password else ""
    db_user = models.User(email=user.email, hashed_password=hashed_password)
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user

# --- Note Functions ---
def create_note(db: Session, note: NoteCreate, user_id: int):
    # Summary will be generated by AI service after note creation
    db_note = models.Note(
        title=note.title, 
        content=note.content, 
        user_id=user_id,
        summary=None,  # Will be set by AI service
        created_at=datetime.datetime.utcnow(), # <-- Add created_at
        updated_at=datetime.datetime.utcnow()  # <-- Add updated_at
    )
    db.add(db_note)
    db.commit()
    db.refresh(db_note)
    return db_note

def update_note_summary(db: Session, note_id: int, summary: str):
    """Update note summary after AI generation"""
    note = db.query(models.Note).filter(models.Note.note_id == note_id).first()
    if note:
        note.summary = summary
        note.updated_at = datetime.datetime.utcnow()
        db.commit()
        db.refresh(note)
    return note

def get_user_notes(db: Session, user_id: int):
    return db.query(models.Note).filter(models.Note.user_id == user_id).all()

def get_user_note(db: Session, note_id: int, user_id: int):
    return db.query(models.Note).filter(
        models.Note.note_id == note_id,
        models.Note.user_id == user_id
    ).first()

def delete_note(db: Session, note_id: int, user_id: int) -> bool:
    note = db.query(models.Note).filter(models.Note.note_id == note_id, models.Note.user_id == user_id).first()
    if not note:
        return False
    db.delete(note)
    db.commit()
    return True

# --- NEW QUIZ CRUD FUNCTIONS ---

def create_quiz(db: Session, quiz: QuizCreate, note_id: int, user_id: int) -> models.Quiz:
    db_quiz = models.Quiz(
        title=quiz.title,
        note_id=note_id,
        user_id=user_id
    )
    db.add(db_quiz)
    db.commit()
    db.refresh(db_quiz)
    return db_quiz

def create_question(db: Session, question: QuestionCreate, quiz_id: int) -> models.Question:
    db_question = models.Question(
        quiz_id=quiz_id,
        question_text=question.question_text,
        options=json.dumps(question.options), # Store list as JSON string
        correct_answer=question.correct_answer
    )
    db.add(db_question)
    db.commit()
    db.refresh(db_question)
    return db_question

def get_quiz(db: Session, quiz_id: int, user_id: int) -> models.Quiz | None:
    return db.query(models.Quiz).filter(
        models.Quiz.quiz_id == quiz_id,
        models.Quiz.user_id == user_id
    ).first()

def delete_quiz(db: Session, quiz_id: int, user_id: int) -> bool:
    quiz = db.query(models.Quiz).filter(models.Quiz.quiz_id == quiz_id, models.Quiz.user_id == user_id).first()
    if not quiz:
        return False
    db.delete(quiz)
    db.commit()
    return True

def get_quiz_questions(db: Session, quiz_id: int) -> list[models.Question]:
    return db.query(models.Question).filter(models.Question.quiz_id == quiz_id).all()

def create_quiz_attempt(db: Session, quiz_id: int, user_id: int, score: float, answers_json: str | None = None) -> models.UserQuizAttempt:
    db_attempt = models.UserQuizAttempt(
        quiz_id=quiz_id,
        user_id=user_id,
        score=score,
        answers_json=answers_json
    )
    db.add(db_attempt)
    db.commit()
    db.refresh(db_attempt)
    return db_attempt

def get_quiz_history_for_user(db: Session, user_id: int) -> list[models.UserQuizAttempt]:
    return db.query(models.UserQuizAttempt).filter(
        models.UserQuizAttempt.user_id == user_id
    ).order_by(models.UserQuizAttempt.completed_at.desc()).all()

# --- END NEW QUIZ CRUD FUNCTIONS ---

# --- Stats Functions ---
def get_user_stats(db: Session, user_id: int):
    total_notes = db.query(models.Note).filter(models.Note.user_id == user_id).count()
    quizzes_taken = db.query(models.UserQuizAttempt).filter(models.UserQuizAttempt.user_id == user_id).count()

    avg_score_query = db.query(func.avg(models.UserQuizAttempt.score)).filter(models.UserQuizAttempt.user_id == user_id).scalar()
    average_score = round(avg_score_query, 2) if avg_score_query is not None else None

    return UserStats(
        total_notes=total_notes,
        quizzes_taken=quizzes_taken,
        average_score=average_score
    )

# --- Nudge Functions ---
async def get_daily_nudge(db: Session, user_id: int): 
    """Get a personalized nudge based on user's recent journal mood"""
    from services import ai_service
    import json
    
    # Get recent journal entries with mood data
    recent_entries = db.query(models.JournalEntry).filter(
        models.JournalEntry.user_id == user_id
    ).order_by(models.JournalEntry.created_at.desc()).limit(5).all()
    
    # Extract mood information from recent entries
    recent_moods = []
    current_mood = "neutral"
    
    for entry in recent_entries:
        if entry.emotions:
            try:
                emotions_data = json.loads(entry.emotions)
                sentiment = emotions_data.get("sentiment", "neutral")
                recent_moods.append(sentiment)
                if len(recent_moods) == 1:  # Use most recent entry's mood
                    current_mood = sentiment
            except:
                pass
    
    # Use most recent mood if available
    if recent_moods:
        current_mood = recent_moods[0]
    
    # Generate personalized nudge based on mood using AI
    try:
        nudge_content = await ai_service.generate_mood_based_nudge(current_mood, recent_moods)
    except Exception as e:
        print(f"Error generating AI nudge: {e}")
        # Fallback to generic nudges
        nudges = {
            "positive": "Great to see you're feeling positive! Keep up the momentum and tackle your studies with this energy!",
            "negative": "It sounds like you're going through a tough time. Remember to take breaks and be kind to yourself. You've got this!",
            "neutral": "A little progress each day adds up to big results. Keep going!"
        }
        nudge_content = nudges.get(current_mood, "A little progress each day adds up to big results.")
    
    return DailyNudge(content=nudge_content)

# --- Quiz History Functions ---
def get_quiz_history(db: Session, user_id: int, limit: int = 5):
    attempts = db.query(models.UserQuizAttempt)\
        .join(models.Quiz)\
        .filter(models.UserQuizAttempt.user_id == user_id)\
        .order_by(models.UserQuizAttempt.completed_at.desc())\
        .limit(limit)\
        .all()
    
    attempts.reverse() 

    return [
        QuizHistoryItem(
            name=attempt.quiz.title, # Get title from joined quiz
            score=int(round(attempt.score))
        ) for attempt in attempts
    ]

# --- Achievements ---
def has_achievement(db: Session, user_id: int, key: str) -> bool:
    return db.query(models.Achievement).filter(models.Achievement.user_id == user_id, models.Achievement.key == key).first() is not None

def unlock_achievement(db: Session, user_id: int, key: str, title: str) -> models.Achievement | None:
    if has_achievement(db, user_id, key):
        return None
    ach = models.Achievement(user_id=user_id, key=key, title=title)
    db.add(ach)
    db.commit()
    db.refresh(ach)
    return ach

def get_user_achievements(db: Session, user_id: int) -> list[models.Achievement]:
    return db.query(models.Achievement).filter(models.Achievement.user_id == user_id).order_by(models.Achievement.earned_at.desc()).all()

def increment_progress(db: Session, user_id: int, key: str) -> int:
    prog = db.query(models.AchievementProgress).filter(models.AchievementProgress.user_id == user_id, models.AchievementProgress.key == key).first()
    if not prog:
        prog = models.AchievementProgress(user_id=user_id, key=key, count=0)
        db.add(prog)
    prog.count = (prog.count or 0) + 1
    db.commit()
    db.refresh(prog)
    return prog.count

def create_journal_entry(db: Session, entry: JournalEntryCreate, user_id: int) -> models.JournalEntry:
    db_entry = models.JournalEntry(
        user_id=user_id,
        title=entry.title,
        content=entry.content,
        created_at=datetime.datetime.utcnow()
    )
    db.add(db_entry)
    db.commit()
    db.refresh(db_entry)
    return db_entry

def get_journal_entry(db: Session, entry_id: int, user_id: int) -> Optional[models.JournalEntry]:
    return db.query(models.JournalEntry).filter(
        models.JournalEntry.entry_id == entry_id,
        models.JournalEntry.user_id == user_id
    ).first()

def delete_journal_entry(db: Session, entry_id: int, user_id: int) -> bool:
    entry = db.query(models.JournalEntry).filter(models.JournalEntry.entry_id == entry_id, models.JournalEntry.user_id == user_id).first()
    if not entry:
        return False
    db.delete(entry)
    db.commit()
    return True

def get_journal_entries_by_user(db: Session, user_id: int, skip: int = 0, limit: int = 100) -> List[models.JournalEntry]:
    return db.query(models.JournalEntry).filter(
        models.JournalEntry.user_id == user_id
    ).order_by(models.JournalEntry.created_at.desc()).offset(skip).limit(limit).all()

def update_journal_entry_ai_fields(
    db: Session, 
    entry: models.JournalEntry, 
    summary: str, 
    emotions: str, 
    ai_nudge: str
) -> models.JournalEntry:
    entry.summary = summary
    entry.emotions = emotions
    entry.ai_nudge = ai_nudge
    entry.updated_at = datetime.datetime.utcnow()
    db.add(entry)
    db.commit()
    db.refresh(entry)
    return entry

# --- Flashcard Functions ---
def create_flashcard(db: Session, note_id: int, question_text: str, answer_text: str) -> models.Flashcard:
    db_flashcard = models.Flashcard(
        note_id=note_id,
        question_text=question_text,
        answer_text=answer_text,
        created_at=datetime.datetime.utcnow()
    )
    db.add(db_flashcard)
    db.commit()
    db.refresh(db_flashcard)
    return db_flashcard

def get_flashcards_for_note(db: Session, note_id: int, user_id: int) -> List[models.Flashcard]:
    """Get all flashcards for a note, ensuring user owns the note"""
    note = get_user_note(db, note_id, user_id)
    if not note:
        return []
    return db.query(models.Flashcard).filter(models.Flashcard.note_id == note_id).all()

def delete_flashcard(db: Session, flashcard_id: int, user_id: int) -> bool:
    """Delete a flashcard if user owns the associated note"""
    flashcard = db.query(models.Flashcard).filter(models.Flashcard.flashcard_id == flashcard_id).first()
    if flashcard:
        note = get_user_note(db, flashcard.note_id, user_id)
        if note:
            db.delete(flashcard)
            db.commit()
            return True
    return False

# --- Calendar Event Functions ---
def create_calendar_event(db: Session, event, user_id: int) -> models.CalendarEvent:
    from schemas.calendar import CalendarEventCreate
    db_event = models.CalendarEvent(
        user_id=user_id,
        title=event.title,
        description=event.description,
        start_time=event.start_time,
        end_time=event.end_time,
        event_type=event.event_type or "study"
    )
    db.add(db_event)
    db.commit()
    db.refresh(db_event)
    return db_event

def get_calendar_events(db: Session, user_id: int, start_date: Optional[datetime.datetime] = None, end_date: Optional[datetime.datetime] = None) -> List[models.CalendarEvent]:
    query = db.query(models.CalendarEvent).filter(models.CalendarEvent.user_id == user_id)
    if start_date:
        query = query.filter(models.CalendarEvent.start_time >= start_date)
    if end_date:
        query = query.filter(models.CalendarEvent.start_time <= end_date)
    return query.order_by(models.CalendarEvent.start_time.asc()).all()

def get_calendar_event(db: Session, event_id: int, user_id: int) -> Optional[models.CalendarEvent]:
    return db.query(models.CalendarEvent).filter(
        models.CalendarEvent.event_id == event_id,
        models.CalendarEvent.user_id == user_id
    ).first()

def update_calendar_event(db: Session, event_id: int, user_id: int, **kwargs) -> Optional[models.CalendarEvent]:
    event = get_calendar_event(db, event_id, user_id)
    if not event:
        return None
    for key, value in kwargs.items():
        if hasattr(event, key) and value is not None:
            setattr(event, key, value)
    event.updated_at = datetime.datetime.utcnow()
    db.add(event)
    db.commit()
    db.refresh(event)
    return event

def delete_calendar_event(db: Session, event_id: int, user_id: int) -> bool:
    event = get_calendar_event(db, event_id, user_id)
    if not event:
        return False
    db.delete(event)
    db.commit()
    return True