"""Change Question.options to Text

Revision ID: 3b47b359560b
Revises: 84b53b71d9f5
Create Date: 2025-10-31 20:34:12.003418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b47b359560b'
down_revision: Union[str, Sequence[str], None] = '84b53b71d9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_entry_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_study_sessions_session_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_flashcards_flashcard_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_nudges_nudge_id'), table_name='nudges')
    op.drop_table('nudges')
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('notes', 'updated_at')
    op.create_table('nudges',
    sa.Column('nudge_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('nudges_user_id_fkey')),
    sa.PrimaryKeyConstraint('nudge_id', name=op.f('nudges_pkey'))
    )
    op.create_index(op.f('ix_nudges_nudge_id'), 'nudges', ['nudge_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('flashcard_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], name=op.f('flashcards_note_id_fkey')),
    sa.PrimaryKeyConstraint('flashcard_id', name=op.f('flashcards_pkey'))
    )
    op.create_index(op.f('ix_flashcards_flashcard_id'), 'flashcards', ['flashcard_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('session_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], name=op.f('study_sessions_note_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('study_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('study_sessions_pkey'))
    )
    op.create_index(op.f('ix_study_sessions_session_id'), 'study_sessions', ['session_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('entry_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entry_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('detected_emotion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('journal_entries_user_id_fkey')),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('journal_entries_pkey'))
    )
    op.create_index(op.f('ix_journal_entries_entry_id'), 'journal_entries', ['entry_id'], unique=False)
    # ### end Alembic commands ###
