"""Add quiz models

Revision ID: 84b53b71d9f5
Revises: 2802afc638db
Create Date: 2025-10-31 20:04:20.572152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84b53b71d9f5'
down_revision: Union[str, Sequence[str], None] = '2802afc638db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_entry_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_journals_journal_id'), table_name='journals')
    op.drop_index(op.f('ix_journals_title'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_nudges_nudge_id'), table_name='nudges')
    op.drop_table('nudges')
    op.drop_index(op.f('ix_study_sessions_session_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_flashcards_flashcard_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.alter_column('notes', 'summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('questions', 'question_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('questions', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('quizzes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quizzes_title'), 'quizzes', ['title'], unique=False)
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['user_id'])
    op.alter_column('user_quiz_attempts', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_quiz_attempts', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_index(op.f('ix_quizzes_title'), table_name='quizzes')
    op.drop_column('quizzes', 'user_id')
    op.alter_column('questions', 'options',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('questions', 'question_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notes', 'summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('flashcards',
    sa.Column('flashcard_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], name=op.f('flashcards_note_id_fkey')),
    sa.PrimaryKeyConstraint('flashcard_id', name=op.f('flashcards_pkey'))
    )
    op.create_index(op.f('ix_flashcards_flashcard_id'), 'flashcards', ['flashcard_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('session_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], name=op.f('study_sessions_note_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('study_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('study_sessions_pkey'))
    )
    op.create_index(op.f('ix_study_sessions_session_id'), 'study_sessions', ['session_id'], unique=False)
    op.create_table('nudges',
    sa.Column('nudge_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('nudges_user_id_fkey')),
    sa.PrimaryKeyConstraint('nudge_id', name=op.f('nudges_pkey'))
    )
    op.create_index(op.f('ix_nudges_nudge_id'), 'nudges', ['nudge_id'], unique=False)
    op.create_table('journals',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('journals_user_id_fkey')),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('journals_pkey'))
    )
    op.create_index(op.f('ix_journals_title'), 'journals', ['title'], unique=False)
    op.create_index(op.f('ix_journals_journal_id'), 'journals', ['journal_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('entry_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entry_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('detected_emotion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('journal_entries_user_id_fkey')),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('journal_entries_pkey'))
    )
    op.create_index(op.f('ix_journal_entries_entry_id'), 'journal_entries', ['entry_id'], unique=False)
    # ### end Alembic commands ###
