"""create calendar_events table

Revision ID: feb186ff7a00
Revises: 7e9b95d75b8c
Create Date: 2025-11-06 15:41:39.753193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feb186ff7a00'
down_revision: Union[str, Sequence[str], None] = '7e9b95d75b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goals_goal_id'), table_name='goals')
    op.drop_table('goals')
    op.add_column('calendar_events', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('calendar_events', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.alter_column('calendar_events', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_calendar_events_user_start'), table_name='calendar_events')
    op.create_index(op.f('ix_calendar_events_start_time'), 'calendar_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.drop_column('calendar_events', 'is_recurring')
    op.drop_column('calendar_events', 'recurrence_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('recurrence_rule', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('calendar_events', sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_time'), table_name='calendar_events')
    op.create_index(op.f('ix_calendar_events_user_start'), 'calendar_events', ['user_id', 'start_time'], unique=False)
    op.alter_column('calendar_events', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('calendar_events', 'is_completed')
    op.drop_column('calendar_events', 'reminder_sent')
    op.create_table('goals',
    sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('goal_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('goals_user_id_fkey')),
    sa.PrimaryKeyConstraint('goal_id', name=op.f('goals_pkey'))
    )
    op.create_index(op.f('ix_goals_goal_id'), 'goals', ['goal_id'], unique=False)
    # ### end Alembic commands ###
